#ifdef LTENGINE_COMPONENT_C_API

#include <LTEngine/c_api/list/linked_list.h>

LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_u8,  u8);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_u16, u16);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_u32, u32);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_u64, u64);

LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_i8,  i8);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_i16, i16);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_i32, i32);
LTENGINE_DEFINE_LINKED_LIST_LOGIC(LTEngine_i64, i64);

#endif