#ifdef LTCORE_COMPONENT_C_API

#include <LTCore/c_api/list/linked_list.h>

LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_u8,  u8);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_u16, u16);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_u32, u32);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_u64, u64);

LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_i8,  i8);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_i16, i16);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_i32, i32);
LTCORE_DEFINE_LINKED_LIST_LOGIC(LTCore_i64, i64);

#endif